In [15]:
import torch
import numpy as np

In [16]:
#Tensors direct initialization
data=[[1,9],[2,8]]
x_data=torch.tensor(data)
print(x_data)

tensor([[1, 9],
        [2, 8]])


In [17]:
#from numpy
data1 = np.array(data)
y_data=torch.from_numpy(data1)
print(y_data)

tensor([[1, 9],
        [2, 8]], dtype=torch.int32)


In [18]:
#from another tensor
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor:\n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Ones Tensor:\n {x_rand} \n")


Ones Tensor:
 tensor([[1, 1],
        [1, 1]]) 

Ones Tensor:
 tensor([[0.2788, 0.6655],
        [0.6463, 0.6118]]) 



In [19]:
#with constat or random values
shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor} \n")

Random Tensor: 
 tensor([[0.6606, 0.1193, 0.8207],
        [0.4279, 0.0700, 0.8293]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



In [20]:
#tensor attributes
print(f"Shape of tensor: {rand_tensor.shape}")
print(f"Datatype of tensor: {rand_tensor.dtype}")
print(f"Device tensor is stored on: {rand_tensor.device}")

Shape of tensor: torch.Size([2, 3])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [21]:
#move to the GPU
if torch.cuda.is_available():
    rand_tensor = rand_tensor.to('cuda')
    print(f"Device tensor is stored on: {rand_tensor.device}")

Device tensor is stored on: cuda:0


In [22]:
#standard indexing
tensor = torch.ones(4,4)
tensor[:,1] = 0
print(f"tensor: \n {tensor} \n")

tensor: 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 



In [23]:
#joining tensors
t1 = torch.cat([tensor,tensor,tensor,tensor],dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [24]:
#element-wise multiplipcation tensor
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
print(f"tensor * tensor \n {tensor * tensor}")

tensor.mul(tensor) 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor * tensor 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [25]:
#matrix multiplication tensor
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.matmul(tensor.T) 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor @ tensor.T 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In [26]:
#addition tensor
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [27]:
#bridge with numpy
t = torch.ones(2,2)
print(f"t: {t}")

n = t.numpy()
print(f"n:{n}")

t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([[1., 1.],
        [1., 1.]])
n:[[1. 1.]
 [1. 1.]]
t: tensor([[2., 2.],
        [2., 2.]])
n: [[2. 2.]
 [2. 2.]]


In [28]:
#numpy array to tensor
n = np.ones(5)
t = torch.from_numpy(n)

np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
